#wordpress application
version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - /mnt/docker-swarm/wordpress/:/var/www/html/wp-content
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 200M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=docker-apps"
        - "traefik.http.routers.http-router1.entrypoints=web"
        - "traefik.http.routers.http-router1.rule=Host(`omer.com`)"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.http.services.wordpress.loadbalancer.sticky=true"
        - "traefik.http.services.wordpress.loadbalancer.sticky.cookie.name=wp-elif"
        - "traefik.http.services.wordpress.loadbalancer.healthcheck.port=80"
          #- "traefik.backend.loadbalancer.method=drr"

    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=elif
      - WORDPRESS_DB_PASSWORD=elif
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_TABLE_PREFIX=elif
    networks:
      docker-apps:

  db:
    image: mysql:5
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 800M
      placement:
        constraints:
          - "node.role==worker"
    environment:
      - MYSQL_ROOT_PASSWORD=elif
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=elif
      - MYSQL_PASSWORD=elif
      - MYSQL_DATABASE=wordpress
    volumes:
      - /mnt/docker-swarm/mysql:/var/lib/mysql
    networks:
      docker-apps:
        ipv4_address: 10.0.5.5
      


  loadbalancer:
    image: traefik
    #command:
    ports:
      - 80:80
      - 8080:8080
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/centos/swarm-file/config.yml:/etc/traefik/traefik.yml
      - /mnt/docker-swarm/logs:/var/log
    deploy:
      resources:
        limits:
         memory: 250M
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints:
          - "node.role == manager"
    networks:
      docker-apps:
   

    

networks:
  docker-apps:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.5.0/24


